### ISSUE TITLE
Podman Install Failing

### ISSUE THREAD

**Issue by codrcodz** [kubic-project/issues#11] opened 2020-07-29 21:59 UTC
Greetings,

When attempting to install podman onto CentOS8 using the Kubic RPM repositories, it appears as though there is an issue with the podman package install. You can replicate this issue by attempting a `docker build .` with the following simple Dockerfile:

```
FROM centos:8
RUN cat /etc/*release \
    && uname -a \
    && dnf -y install wget \
    && dnf -y module disable container-tools \
    && cd /etc/yum.repos.d/ \
    && wget https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/CentOS_8/devel:kubic:libcontainers:stable.repo \
    && for repo in *; do echo -e "\nRepo: $repo"; while read -r line; do echo "$line"; done < "$repo"; done \ 
    && dnf -y install podman;
```

Here is an excerpt showing the error:

```
Dependencies resolved.
================================================================================
 Package                       ArchVersion                         Repository                       Size
================================================================================
Installing:
 podman                        x86_642.0.3-1.el8                     devel_kubic_libcontainers_stable 23 M
Upgrading:
 iptables-libs                 x86_641.8.4-10.el8                    BaseOS                           105 k
Installing dependencies:
 iptables                      x86_641.8.4-10.el8                    BaseOS                           581 k
 jansson                       x86_642.11-3.el8                      BaseOS                           46 k
 libnetfilter_conntrack        x86_641.0.6-5.el8                     BaseOS                           65 k
 libnfnetlink                  x86_641.0.1-13.el8                    BaseOS                           33 k
 libnftnl                      x86_641.1.5-4.el8                     BaseOS                           83 k
 nftables                      x86_641:0.9.3-12.el8                  BaseOS                           311 k
 conmon                        x86_642:2.0.20-1.el8                  devel_kubic_libcontainers_stable 44 k
 containernetworking-plugins   x86_640.8.6-1.el8                     devel_kubic_libcontainers_stable 36 M
 containers-common             x86_642:1.1.1-1.el8                   devel_kubic_libcontainers_stable 76 k
 libslirp                      x86_644.2.0-2.el8                     devel_kubic_libcontainers_stable 67 k
 podman-plugins                x86_642.0.3-1.el8                     devel_kubic_libcontainers_stable 2.3 M
Installing weak dependencies:
 catatonit                     x86_640.1.5-2.el8                     devel_kubic_libcontainers_stable 288 k
 libvarlink-util               x86_6419-3.el8                        devel_kubic_libcontainers_stable 51 k
 runc                          x86_642:1.0.0-145.rc91.git24a3cf8.el8 devel_kubic_libcontainers_stable 5.8 M
 slirp4netns                   x86_641.1.4-1.el8                     devel_kubic_libcontainers_stable 52 k

Transaction Summary
================================================================================
Install  16 Packages
Upgrade   1 Package

Total download size: 69 M
Downloading Packages:
(1/17): jansson-2.11-3.el8.x86_64.rpm           129 kB/s |  46 kB     00:00    
(2/17): libnetfilter_conntrack-1.0.6-5.el8.x86_ 150 kB/s |  65 kB     00:00    
(3/17): libnfnetlink-1.0.1-13.el8.x86_64.rpm    238 kB/s |  33 kB     00:00    
(4/17): libnftnl-1.1.5-4.el8.x86_64.rpm         349 kB/s |  83 kB     00:00    
(5/17): nftables-0.9.3-12.el8.x86_64.rpm        642 kB/s | 311 kB     00:00    
(6/17): iptables-1.8.4-10.el8.x86_64.rpm        543 kB/s | 581 kB     00:01    
(7/17): catatonit-0.1.5-2.el8.x86_64.rpm        194 kB/s | 288 kB     00:01    
(8/17): conmon-2.0.20-1.el8.x86_64.rpm           23 kB/s |  44 kB     00:01    
(9/17): libslirp-4.2.0-2.el8.x86_64.rpm         157 kB/s |  67 kB     00:00    
(10/17): containers-common-1.1.1-1.el8.x86_64.r  62 kB/s |  76 kB     00:01    
(11/17): libvarlink-util-19-3.el8.x86_64.rpm    113 kB/s |  51 kB     00:00    
[MIRROR] podman-2.0.3-1.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 23829532 but expected size is: 23829556
[FAILED] podman-2.0.3-1.el8.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Cannot download x86_64/podman-2.0.3-1.el8.x86_64.rpm: All mirrors were tried
```

A colleague of mine originally found this error while attempting the same install in a VM and asked me to replicate it on my system just in case it was network connectivity or environment related. Even on his system though, he consistently gets the same error for the same package, and is able to consistently and successfully install other packages from your repo without issue.

**Comment by codrcodz** [comment] 2020-07-29 22:07
Additonally, using the same Dockerfile, but replacing `podman` for `podman-plugins` in the last line yields this result:

```
Dependencies resolved.
================================================================================
 Package         Arch    Version        Repository                         Size
================================================================================
Installing:
 podman-plugins  x86_64  2.0.3-1.el8    devel_kubic_libcontainers_stable  2.3 M

Transaction Summary
================================================================================
Install  1 Package

Total download size: 2.3 M
Installed size: 5.9 M
Downloading Packages:
[MIRROR] podman-plugins-2.0.3-1.el8.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: c737c1a1690e5cb01246198b7075a6f32768aa090862d2f9a80edd190a78dc4a(sha256)  Expected: 65d36e1068c44bea9852bc267a8694cb1239fd7eeb3ac8a36d324d53ac476e7b(sha256) 
[FAILED] podman-plugins-2.0.3-1.el8.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Cannot download x86_64/podman-plugins-2.0.3-1.el8.x86_64.rpm: All mirrors were tried
```

**Comment by codrcodz** [comment] 2020-08-13 19:08
Looks like it is working now, but leaving this open for retro to prevent regression.

**Comment by sysrich** [comment] 2020-08-25 13:30
This issue tracker is for issues with the openSUSE Kubic Project, not with the podman packages we voluntarily host for other distributions. I'm glad it's fixed, closing this bug because the team following this tracker are in no position to prevent any regression.

**Closed as completed by sysrich** 2020-08-25 13:30 UTC

**Comment by codrcodz** [comment] 2020-08-25 14:21
@sysrich shortly after my last comment we started having the same problem, with a different package. Based on the error messages, this appears to be a problem with the environment the packages are hosted in, not the packages themselves.
